name: foodnet
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  material_design_icons_flutter: ^4.0.5755
  carousel_slider: ^2.3.1
  flutter_staggered_grid_view: ^0.3.2
  badges: ^1.1.6
  flutter_launcher_icons: ^0.8.1
  google_fonts: ^1.1.1

flutter_icons: 
  android: "launcher_icon"
  ios: true
  image_path: "images/mumbai.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - data/products.json
    - data/bestSelling.json
    - images/logo.png
    - images/mumbai.png
    - images/snacks.png
    - images/farsan.png
    - images/sweets.png
    - images/dry_fruits.png
    - images/chocolate.png
    - images/top_picks/5Star.png
    - images/top_picks/free.png
    - images/top_picks/ghughra.png
    - images/top_picks/chivda.png
    - images/top_picks/goldCoin.png
    - images/top_picks/ladoo.png
    - images/top_picks/peda.png
    - images/top_offers/offer1.png
    - images/top_offers/offer2.png
    - images/top_offers/offer3.png
    - images/top_offers/offer4.png
    - images/best_selling/best1.png
    - images/best_selling/best2.png
    - images/best_selling/best3.png
    - images/best_selling/best4.png
    - images/best_selling/best5.png
    
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
